blank_issues_enabled: false
contact_links:
  - name: Discord Community
    url: https://discord.gg/4GTNbEy5EB
    about: Ask questions and discuss with community members
  - name: Contributing Documentation
    url: https://github.com/Proact0/act-operator/blob/main/CONTRIBUTING.md
    about: Read the Act Operator contributing documentation
